#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
count_and_annotate.py
=====================
Đếm # Subject-attr, Object-attr, Context-attr, Actions per dataset
→ In bảng theo mẫu luận văn
→ Ghi metadata vào policy_dataset.json (trường dataset_statistics)

Chạy: python scripts/count_and_annotate.py
"""
import sys, io, json, csv, os, re, collections

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POLICY_PATH  = os.path.join(PROJECT_ROOT, "dataset", "policy_dataset.json")
SHEET_PATH   = os.path.join(PROJECT_ROOT, "dataset", "annotation_sheet.csv")
LLM_GOLD     = os.path.join(PROJECT_ROOT, "dataset", "annotation_llm_gold.csv")

# ─── Xác định nguồn iTrust từ annotation_sheet.csv ───────────────────────────
ITRUST_SOURCES = {"t2p", "acre"}

def load_itrust_counts():
    """
    Đếm từ annotation_sheet.csv:
      - #sentences  : số câu có source trong ITRUST_SOURCES
      - #context    : tổng số gold context (temporal_final OR spatial_final) per câu
    """
    n_sents = 0
    n_ctx   = 0
    if not os.path.exists(SHEET_PATH):
        return n_sents, n_ctx
    with open(SHEET_PATH, encoding='utf-8-sig', newline='') as f:
        for row in csv.DictReader(f):
            src = row.get("Source", "").strip().lower()
            if src not in ITRUST_SOURCES:
                continue
            sent = row.get("Sentence", "").strip()
            if not sent:
                continue
            n_sents += 1
            tf = row.get("temporal_final", "").strip()
            sf = row.get("spatial_final",  "").strip()
            if tf: n_ctx += 1
            if sf: n_ctx += 1
    return n_sents, n_ctx

def load_kma_counts(policies, llm_gold_map):
    """
    Đếm từ policy_dataset.json (380 câu = Collected KMA_ACP):
      - #sentences   : len(policies)
      - #subject_attr: attributes[category=subject]
      - #object_attr : attributes[category=object]
      - #context_attr: context gold từ llm_gold_map (temporal + spatial) mỗi câu
      - #actions     : actions[]
    """
    n_sents = 0
    n_subj  = 0
    n_obj   = 0
    n_ctx   = 0
    n_act   = 0

    for pol in policies:
        sent = pol.get("sentence", "").strip()
        if not sent:
            continue
        n_sents += 1

        attrs = pol.get("attributes", [])
        for a in attrs:
            cat = a.get("category", "")
            if   cat == "subject": n_subj += 1
            elif cat == "object":  n_obj  += 1

        acts = pol.get("actions", [])
        n_act += len([a for a in acts if a])

        # Context: ưu tiên llm_gold_map, fallback environment[]
        if sent in llm_gold_map and llm_gold_map[sent]:
            n_ctx += len(llm_gold_map[sent])
        else:
            for env in pol.get("environment", []):
                val = env.get("full_value") or env.get("normalized", "")
                if val: n_ctx += 1

    return n_sents, n_subj, n_obj, n_ctx, n_act

def load_llm_gold():
    """Returns dict[sentence → list of non-empty context strings]."""
    result = {}
    if not os.path.exists(LLM_GOLD):
        return result
    with open(LLM_GOLD, encoding='utf-8-sig', newline='') as f:
        for row in csv.DictReader(f):
            sent = row.get("Sentence", "").strip()
            if not sent: continue
            ctx = []
            for field in ("temporal_final", "spatial_final"):
                v = row.get(field, "").strip()
                if v: ctx.append(v)
            if sent not in result:
                result[sent] = []
            result[sent].extend(ctx)
    return result

# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    # Load
    with open(POLICY_PATH, encoding='utf-8') as f:
        pdata = json.load(f)
    policies = pdata.get("policies", [])

    llm_gold = load_llm_gold()

    # Count
    it_sents, it_ctx                       = load_itrust_counts()
    km_sents, km_subj, km_obj, km_ctx, km_act = load_kma_counts(policies, llm_gold)

    # ── Ghi metadata vào policy_dataset.json ──────────────────────────────────
    pdata["dataset_statistics"] = {
        "_note": "Auto-generated by scripts/count_and_annotate.py",
        "iTrust": {
            "source":              ["t2p", "acre"],
            "sentences":           it_sents,
            "subject_attributes":  "N/A (not annotated)",
            "object_attributes":   "N/A (not annotated)",
            "context_attributes":  it_ctx,
            "actions":             "N/A (not annotated)"
        },
        "Collected_KMA_ACP": {
            "source":              ["policy_dataset.json"],
            "sentences":           km_sents,
            "subject_attributes":  km_subj,
            "object_attributes":   km_obj,
            "context_attributes":  km_ctx,
            "actions":             km_act
        }
    }

    # Ghi lại file
    with open(POLICY_PATH, 'w', encoding='utf-8') as f:
        json.dump(pdata, f, ensure_ascii=False, indent=4)
    print(f"[OK] Đã ghi dataset_statistics vào: {POLICY_PATH}\n")

    # ── In bảng ───────────────────────────────────────────────────────────────
    W1, W2, W3 = 20, 14, 10
    sep = "+-" + "-"*W1 + "-+-" + "-"*W2 + "-+" + ("-"*W3 + "-+")*4

    def row(ds, sents, sa, oa, ca, act):
        def fmt(v):
            return f"{v:>{W3}}" if isinstance(v, int) else f"{'N/A':>{W3}}"
        return (f"| {ds:<{W1}} | {str(sents):>{W2}} | "
                f"{fmt(sa)} | {fmt(oa)} | {fmt(ca)} | {fmt(act)} |")

    print(sep)
    print(f"| {'Dataset':<{W1}} | {'ACP sentences':>{W2}} | "
          f"{'#Subj-attr':>{W3}} | {'#Obj-attr':>{W3}} | "
          f"{'#Ctx-attr':>{W3}} | {'#Actions':>{W3}} |")
    print(sep)
    print(row("iTrust",            it_sents, "N/A", "N/A", it_ctx,  "N/A"))
    print(row("Collected KMA_ACP", km_sents, km_subj, km_obj, km_ctx, km_act))
    print(sep)

    # Tổng
    print(row("TOTAL",
              it_sents + km_sents,
              km_subj,
              km_obj,
              it_ctx + km_ctx,
              km_act))
    print(sep)

    # Summary
    print(f"""
  SUMMARY:
    iTrust (t2p + acre)     : {it_sents} sentences, {it_ctx} context labels
    Collected KMA_ACP       : {km_sents} sentences
      Subject-attributes    : {km_subj}
      Object-attributes     : {km_obj}
      Context-attributes    : {km_ctx}
      Actions               : {km_act}
""")

if __name__ == "__main__":
    main()
